// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.Filters")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.OrderBys")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.Projection")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.QueryExpression.Select")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Remove(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Remove(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Object)~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Set(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Set(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Object)~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.ODataConnection.ApplyLinkUpdates(GeneXus.Data.NTier.ODataQuery,System.Data.IDataParameterCollection,System.Func{GeneXus.Data.NTier.GXODataClient,System.Data.IDataParameterCollection,GeneXus.Data.NTier.GXODataClient},System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.ODataDataReader.#ctor(GeneXus.Data.NTier.ODataConnection,GeneXus.Data.NTier.GXODataClient,GeneXus.Data.NTier.ServiceCursorDef,System.Data.IDataParameterCollection,System.Data.CommandBehavior)")]
[assembly: SuppressMessage("Usage", "VSTHRD103:Call async methods when in an async method", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.ODataDataReader.#ctor(GeneXus.Data.NTier.ODataConnection,GeneXus.Data.NTier.GXODataClient,GeneXus.Data.NTier.ServiceCursorDef,System.Data.IDataParameterCollection,System.Data.CommandBehavior)")]
