// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Copy(System.String,GxFileType,System.String,GxFileType)~System.String")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Copy(System.String,System.String,System.String,System.String,GxFileType)~System.String")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.CreateDirectory(System.String)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Delete(System.String,GxFileType)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.DeleteDirectory(System.String)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Download(System.String,System.String,GxFileType)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Exists(System.String,GxFileType)~System.Boolean")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.ExistsDirectory(System.String)~System.Boolean")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Get(System.String,GxFileType,System.Int32)~System.String")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetContainer(System.String,Microsoft.WindowsAzure.Storage.Blob.BlobContainerPublicAccessType)~Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetFiles(System.String,System.String)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetLastModified(System.String,GxFileType)~System.DateTime")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetLength(System.String,GxFileType)~System.Int64")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetStream(System.String,GxFileType)~System.IO.Stream")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.GetSubDirectories(System.String)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.RenameDirectory(System.String,System.String)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Upload(System.String,System.IO.Stream,GxFileType)~System.String")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Storage.GXAzureStorage.AzureStorageExternalProvider.Upload(System.String,System.String,GxFileType)~System.String")]
