name: 'Setup .NET Core SDK'
description: 'Set up a specific version of the .NET Core CLI in the PATH'
author: 'GitHub'
branding:
  icon: play
  color: green
inputs: 
  dotnet-version:
    description: '3.1.101'
runs:
  using: 'node12'
  main: 'dist/index.js'