// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA5359:Do Not Disable Certificate Validation", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.ODataConnection.InitializeConnection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.Data.NTier.DataStoreHelperOData.ODataMapCol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.Data.NTier.DataStoreHelperOData.ODataMapDomain")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.Data.NTier.DataStoreHelperOData.ODataMapExt")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.Data.NTier.DataStoreHelperOData.ODataMapName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.Data.NTier.DataStoreHelperOData.Query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.Filters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.OrderBys")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.DataStoreHelperOData.Query.Projection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:GeneXus.Data.NTier.QueryExpression.Select")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.ODataConnection.InitializeConnection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Remove(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Remove(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Object)~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Set(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Collections.Generic.IDictionary{System.String,System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Data.NTier.DataStoreHelperOData.Set(System.Threading.Tasks.Task{Simple.OData.Client.ODataEntry},System.String,System.Object)~System.Collections.Generic.IDictionary{System.String,System.Object}")]