// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.WebControls.FontUnit")]
[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:GeneXus.WebControls.Unit")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GXBCRestService.ErrorCheck(GeneXus.Utils.IGxSilentTrn)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GxClasses.Web.IGXRouting.ProcessRestRequest(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Notifications.WebSocket.WebSocketHandler.OnMessage(System.String,System.Net.WebSockets.WebSocket,System.Net.WebSockets.WebSocketReceiveResult,System.Byte[])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Notifications.WebSocket.WebSocketManagerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Notifications.WebSocket.WebSocketManagerMiddleware.ReadDataFromSocket(System.Net.WebSockets.WebSocket,System.Byte[],System.IO.MemoryStream)~System.Threading.Tasks.Task{System.Net.WebSockets.WebSocketReceiveResult}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Notifications.WebSocket.WebSocketManagerMiddleware.Receive(System.Net.WebSockets.WebSocket,System.Action{System.Net.WebSockets.WebSocketReceiveResult,System.Byte[]})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.MethodBodyExecute(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Post~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.MethodUrlExecute(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Patch(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.SetError(Microsoft.AspNetCore.Http.HttpContext,System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.SetError(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.WebException(System.Exception)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Serialize(System.Collections.Generic.Dictionary{System.String,System.Object},System.Collections.Generic.Dictionary{System.String,System.String},System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Serialize(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD101:Avoid unsupported async delegates", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Notifications.WebSocket.WebSocketManagerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD110:Observe result of async calls", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Http.WebSocket.WSHandler.SendMessage(System.Net.WebSockets.WebSocket,System.String)")]
[assembly: SuppressMessage("Usage", "VSTHRD110:Observe result of async calls", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Http.WebSocket.WebSocketConnectionManager.RemoveSocket(System.String,System.Net.WebSockets.WebSocket)")]
[assembly: SuppressMessage("Usage", "VSTHRD110:Observe result of async calls", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Http.WebSocket.WebSocketConnectionManager.Clear")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Delete(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Get(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.Put(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD110:Observe result of async calls", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.IsAuthenticated(System.String)~System.Boolean")]
[assembly: SuppressMessage("Usage", "VSTHRD110:Observe result of async calls", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.Application.GxRestWrapper.IsAuthenticated(GeneXus.Http.GAMSecurityLevel,System.Boolean,System.String)~System.Boolean")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GxClasses.Web.Middleware.GXRouting.RouteHttpService(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:GeneXus.HttpHandlerFactory.HandlerFactory.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:GX.GXGeolocation.GetContentFromURL(System.String)~System.String")]
