using System;
using System.Collections.Generic;
using System.Text;

//Temporary classes for SDTs generated by nemo. Should be removed.

namespace System.Web.Services.Protocols{
	public class dummy { }
}
namespace System.ServiceModel { }
namespace System.ServiceModel.Activation{
	public class dummy { }
}
namespace System.ServiceModel
{
	
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
	public sealed class XmlSerializerFormatAttribute : Attribute
	{
		
		public XmlSerializerFormatAttribute() { }
	}
}
namespace System.Web.SessionState
{
	
	public interface IRequiresSessionState
	{
	}
}