name: Process commit
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'release-*'
    paths:
      - 'dotnet/**'
    ignore-paths:
      - '*.md'

jobs:
  dispatchWorkflow:
    runs-on: [ubuntu-latest]

    steps:
    - name: Dispatch Workflow
      run: >
        curl -X POST
        -H 'Accept: application/vnd.github.v3+json' 
        -H 'Authorization: token ${{ secrets.SECURE_TOKEN }}' 
        --silent --show-error --fail 
        ${{ secrets.BUILD_WORKFLOW_DISPATCH }} 
        -d '{
          "ref":"master",
           "inputs": { 
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "build-file": "dotnet\\DotNetStandardClasses.sln",
              "package-version": ".\\.github\\generatePackageVersion.ps1",
              "packages-path": ".\\dotnet\\*.nupkg",
              "skip-duplicates": "true"
            }
          }'